project:
  type: website
  output-dir: docs


website:
  title: "DemoGHPage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - visualization.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

